---
name: hk

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  hk:
    uses: hugoh/gh-workflows/.github/workflows/hk.yml@d8b9c2df31a2df9ae138f25ec02633a3427c59a2 # v1.33.2
    permissions:
      contents: read
      packages: read
      statuses: write
    with:
      pre-hk: bun install --frozen-lockfile
